Added more Vnet-to-Vnet PTF test cases
sonic-net/DASH pull request #315
Opened 2023-01-11 15:03 UTC by aputriax

- Added Vnet-to-Vnet test plan
- Added more Vnet-to-Vnet PTF test cases
- Updated sai_dash_utils

Signed-off-by: Yuriy Harhas <yuriyx.harhas@intel.com>

2023-01-18 17:36 UTC, chrispsommers commented on test/docs/testplans/vnet.md
> +More details may be found in [DASH SONiC HLD](https://github.com/Azure/DASH/blob/main/documentation/general/design/dash-sonic-hld.md#15-design-considerations).
Link is broken, `design` was removed from path quite some time ago.
Also, change `Azure` to `sonic-net`

2023-01-18 17:36 UTC, chrispsommers commented on test/docs/testplans/vnet.md
> +Original table [link](https://github.com/Azure/DASH/blob/main/documentation/general/design/sdn-features-packet-transforms.md#routing-routes-and-route-action).
Link is broken, `design` was removed from path quite some time ago.
Also, change `Azure` to `sonic-net`

2023-01-18 18:04 UTC, chrispsommers requested changes
Please fix links, thanks.

2023-03-15 16:51 UTC, chrispsommers commented
@aputriax Can we resolve the final comments? Seems like a trivial edit can finish this up. Thanks.

2023-03-24 10:11 UTC, yharhasx commented
@chrispsommers links were fixed. Also more test cases were added with some minor fixes. If everything seems good for you, please merge.
Thanks!

2023-03-29 16:14 UTC, chrispsommers approved these changes

2023-03-29 16:15 UTC, chrispsommers approved these changes
LGTM, will be nice to get some evidence the skipped test cases work on a real target since bmv2 is lacking underlay.

2023-03-29 16:45 UTC, merged