Change SAI submodule URL to opencomputeproject/master
sonic-net/DASH pull request #346
Opened 2023-02-22 15:49 UTC by vmytnykx

Since PTF VxLAN changes are merged into latest PTF and PTF submodule is updated in official SAI repo by https://github.com/opencomputeproject/SAI/pull/1720, switch DASH to use opencompute SAI repo master branch instead of dev repo that is now.

2023-02-22 17:05 UTC, chrispsommers commented
Seeing a failure in the CI (also in the fork repo from whcih this PR originates). https://github.com/sonic-net/DASH/actions/runs/4244461183/jobs/7378608147#step:14:248
```
/usr/bin/ld: ./obj/sai_rpc_server.o: in function `sai_rpcHandlerFrontend::sai_thrift_api_uninitialize()':
/dash/dash-pipeline/SAI/SAI/test/saithriftv2/../../meta/sai_rpc_frontend.cpp:845: undefined reference to `sai_api_uninitialize'
```
Was a new function `sai_api_uninitialize` added to SAI recently? We may need a dummy function added to DASH libsai.

2023-02-22 17:14 UTC, chrispsommers requested changes
Please see comment in the main conversation thread - CI is failing, we need a new SAI dummy function.

2023-03-01 17:08 UTC, chrispsommers commented
There seems to be some kind of consistent error and it shows up in your own- dev branch CI as well, e.g. https://github.com/reshmaintel/DASH/actions/runs/4305647914/jobs/7508387260#step:17:56

2023-03-29 16:49 UTC, KrisNey-MSFT commented
s/be by end of week

2023-04-04 18:32 UTC, chrispsommers commented
Hi @vmytnykx I see a CI failure, have you synced to main recently?

2023-04-04 20:22 UTC, vmytnykx commented
> Hi @vmytnykx I see a CI failure, have you synced to main recently?

Yes, trying to make PTF work with recent SAI repo now, so CI may fail.

2023-04-05 16:01 UTC, vmytnykx commented
Looks like there was a lot of changes into main/SAI that changed PTF stuff, need some more time to fix integration with latest SAI master.

2023-07-11 09:50 UTC, vmytnykx commented
Handled by https://github.com/sonic-net/DASH/pull/398 

Closing this PR

2023-07-11 09:50 UTC, closed without merging