cleanup in dash testcases
sonic-net/DASH pull request #393
Opened 2023-06-22 19:58 UTC by vincent-xs

addressing a few minor issues encountered and fix locally while running testcases and developping SAI.

dash testcase cleanup:
           return proper objects, fix remove command generation in scale outbound (we need the whole key in the remove command)
update saithrift docker file (-qq is not working on newer docker compose version)
update p4 generation to handle ip prefix list (needed when we compile dash acl with DASH_MATCH to generate the proper SAI API)
add meter functions to sai_dash_utils.py to facilitate testcase writing.

2023-06-28 16:18 UTC, KrisNey-MSFT commented
Perhaps place some GitHub checkboxes to split this up, etc...

2023-06-28 16:25 UTC, chrispsommers approved these changes
LGTM - needs review from someone at Intel to evaluate potential impact. @reshmaintel to assign someone

2023-06-29 11:26 UTC, yharhasx commented
Hi @vincent-xs, thanks for your fixes, they look good to me!
But I have few suggestions regarding Metering API in sai_dash_utils.py:
- As it`s cleanup PR I believe that would be better to introduce metering API changes is separate PR.
- Moreover, we are planning to create a PR with adding of Metering API, CRUD and VNET to VNET test cases in the end of the next week after final run on real HW.

So, to sum up, would it be suitable for you to update your PR without Metering changes? And in case of any suggestions from your side create new one based on our future Metering PR.

2023-06-29 14:32 UTC, vincent-xs commented
> Hi @vincent-xs, thanks for your fixes, they look good to me! But I have few suggestions regarding Metering API in sai_dash_utils.py:
> 
> * As it`s cleanup PR I believe that would be better to introduce metering API changes is separate PR.
> * Moreover, we are planning to create a PR with adding of Metering API, CRUD and VNET to VNET test cases in the end of the next week after final run on real HW.
> 
> So, to sum up, would it be suitable for you to update your PR without Metering changes? And in case of any suggestions from your side create new one based on our future Metering PR.

Yuri,

wrt metering, I can certainly remove those changes (which I used to UT my code change). I got to believe similar changes will show up in the PR you'll be creating to support those new testcases. once your PR gets committed, I'll figure out if those changes even need to be there.

2023-06-29 14:45 UTC, yharhasx commented
> > Hi @vincent-xs, thanks for your fixes, they look good to me! But I have few suggestions regarding Metering API in sai_dash_utils.py:
> > 
> > * As it`s cleanup PR I believe that would be better to introduce metering API changes is separate PR.
> > * Moreover, we are planning to create a PR with adding of Metering API, CRUD and VNET to VNET test cases in the end of the next week after final run on real HW.
> > 
> > So, to sum up, would it be suitable for you to update your PR without Metering changes? And in case of any suggestions from your side create new one based on our future Metering PR.
> 
> Yuri,
> 
> wrt metering, I can certainly remove those changes (which I used to UT my code change). I got to believe similar changes will show up in the PR you'll be creating to support those new testcases. once your PR gets committed, I'll figure out if those changes even need to be there.

Vincent, 
Thanks for understanding! Our code related to metering has changes similar to yours and easily can be used for new test cases development etc.
Thanks again!

2023-06-29 14:55 UTC, yharhasx requested changes

2023-06-29 14:59 UTC, vincent-xs commented on test/test-cases/functional/ptf/sai_dash_utils.py
> +                                                  overlay_dmac=overlay_dmac0,
indeed, I didn't have that in my original diff.

2023-06-29 15:49 UTC, merged