fix for https://github.com/sonic-net/DASH/issues/454
sonic-net/DASH pull request #455
Opened 2023-10-31 22:12 UTC by mgheorghe

eni was not very descriptive and one could assume it is the eni object id, updated the name to clearly specify it is the eni mac

2023-10-31 23:33 UTC, r12f commented
looks like The dash sonic hld is moving to sonic repo while DASH repo will link to the sonic one as reference, so I wonder if we could make the change there. both prince and i should be able to help sign off: https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-sonic-hld.md. 

and here is the PR that I refer to: https://github.com/sonic-net/DASH/pull/447.

2023-10-31 23:44 UTC, prsunny approved these changes

2023-10-31 23:45 UTC, r12f approved these changes

2023-10-31 23:47 UTC, prsunny requested changes
@mgheorghe , changes lgtm, but can you make the change here - https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-sonic-hld.md.

2024-01-17 17:37 UTC, KrisNey-MSFT commented
do not merge yet or cancel

2024-02-07 01:09 UTC, mgheorghe commented
canceling, was a misunderstanding

2024-02-07 01:09 UTC, closed without merging