[doc] Add HLD for Private link and Private Link NSG
sonic-net/DASH pull request #542
Opened 2024-03-29 19:53 UTC by r12f

2024-04-08 21:48 UTC, marian-pritsak requested changes

2024-04-08 21:48 UTC, marian-pritsak commented on documentation/private-link-service/private-link-service.md
> +| entry_attr.SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_TUNNEL_ID | `sai_object_id_t` | (SAI object ID of the NSG tunnel) |
Mapping entry should be also able to point directly to a next hop.

2024-04-24 21:31 UTC, marian-pritsak approved these changes

2024-04-25 20:21 UTC, prsunny commented
@theasianpianist

2024-04-26 18:27 UTC, merged